//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KuFlow.UiPathLibrary.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KuFlow.UiPathLibrary.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A log entry is added to the task. If the number of log entries is reached, the oldest log entry is removed..
        /// </summary>
        public static string AppendALogToTheTask_Description {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Append a log to the task.
        /// </summary>
        public static string AppendALogToTheTask_DisplayName {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log level: INFO, WARN or ERROR.
        /// </summary>
        public static string AppendALogToTheTask_Level_Description {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_Level_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string AppendALogToTheTask_Level_DisplayName {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_Level_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message to add.
        /// </summary>
        public static string AppendALogToTheTask_Message_Description {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string AppendALogToTheTask_Message_DisplayName {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the task to which the log is added.
        /// </summary>
        public static string AppendALogToTheTask_TaskIdentifier_Description {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_TaskIdentifier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Identifier.
        /// </summary>
        public static string AppendALogToTheTask_TaskIdentifier_DisplayName {
            get {
                return ResourceManager.GetString("AppendALogToTheTask_TaskIdentifier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication.
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If set, continue executing the remaining activities even if the current activity has failed..
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContinueOnError.
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do.
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the KuFlow application used to authenticate the activities.
        /// </summary>
        public static string KuFlowScope_ClientId_Description {
            get {
                return ResourceManager.GetString("KuFlowScope_ClientId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId.
        /// </summary>
        public static string KuFlowScope_ClientId_DisplayName {
            get {
                return ResourceManager.GetString("KuFlowScope_ClientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password of the KuFlow application used to authenticate the activities.
        /// </summary>
        public static string KuFlowScope_ClientSecret_Description {
            get {
                return ResourceManager.GetString("KuFlowScope_ClientSecret_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSecret.
        /// </summary>
        public static string KuFlowScope_ClientSecret_DisplayName {
            get {
                return ResourceManager.GetString("KuFlowScope_ClientSecret_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticates all KuFlow activities.
        /// </summary>
        public static string KuFlowScope_Description {
            get {
                return ResourceManager.GetString("KuFlowScope_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KuFlow Scope.
        /// </summary>
        public static string KuFlowScope_DisplayName {
            get {
                return ResourceManager.GetString("KuFlowScope_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to get a process by Id.
        /// </summary>
        public static string RetrieveProcess_Description {
            get {
                return ResourceManager.GetString("RetrieveProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Process.
        /// </summary>
        public static string RetrieveProcess_DisplayName {
            get {
                return ResourceManager.GetString("RetrieveProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process resource.
        /// </summary>
        public static string RetrieveProcess_Process_Description {
            get {
                return ResourceManager.GetString("RetrieveProcess_Process_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string RetrieveProcess_Process_DisplayName {
            get {
                return ResourceManager.GetString("RetrieveProcess_Process_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the process to retrieve.
        /// </summary>
        public static string RetrieveProcess_ProcessIdentifier_Description {
            get {
                return ResourceManager.GetString("RetrieveProcess_ProcessIdentifier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Identifier.
        /// </summary>
        public static string RetrieveProcess_ProcessIdentifier_DisplayName {
            get {
                return ResourceManager.GetString("RetrieveProcess_ProcessIdentifier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to get a task by Id.
        /// </summary>
        public static string RetrieveTask_Description {
            get {
                return ResourceManager.GetString("RetrieveTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve task.
        /// </summary>
        public static string RetrieveTask_DisplayName {
            get {
                return ResourceManager.GetString("RetrieveTask_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the task to retrieve.
        /// </summary>
        public static string RetrieveTask_Task_Description {
            get {
                return ResourceManager.GetString("RetrieveTask_Task_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Identifier.
        /// </summary>
        public static string RetrieveTask_Task_DisplayName {
            get {
                return ResourceManager.GetString("RetrieveTask_Task_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier of the task to which the log is added.
        /// </summary>
        public static string RetrieveTask_TaskIdentifier_Description {
            get {
                return ResourceManager.GetString("RetrieveTask_TaskIdentifier_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Identifier.
        /// </summary>
        public static string RetrieveTask_TaskIdentifier_DisplayName {
            get {
                return ResourceManager.GetString("RetrieveTask_TaskIdentifier_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute)..
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (milliseconds).
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The activity timed out and was canceled..
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value either for {0} or {1}, but not both..
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide values for both {0} and {1}..
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used outside of a {0}..
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for {0}..
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
